# Jupyter Book Configuration
# Learn more at https://jupyterbook.org/customize/config.html

title: Deep Learning Biology Codebook
author: Deep Learning Biology Team
logo: ""
copyright: "2024"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off  # Don't execute during build (notebooks are meant to be run interactively)
  timeout: 300

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: deep_learning_biology_codebook.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/tonyliang19/deep-learning-biology-codebook
  path_to_book: ""
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  extra_footer: |
    <div>
      Created with ❤️ for biology and deep learning enthusiasts
    </div>

# Launch button configuration
launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"

# Parse and render settings
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

sphinx:
  config:
    html_theme_options:
      repository_url: https://github.com/tonyliang19/deep-learning-biology-codebook
      use_repository_button: true
      use_issues_button: true
      use_edit_page_button: true
